/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiSummaryRouteImport } from './routes/ai-summary'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as DataQualityRouteImport } from './routes/data-quality'
import { Route as EnergyRouteImport } from './routes/energy'
import { Route as GaitRouteImport } from './routes/gait'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSummaryRoute = AiSummaryRouteImport.update({
  id: '/ai-summary',
  path: '/ai-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const DataQualityRoute = DataQualityRouteImport.update({
  id: '/data-quality',
  path: '/data-quality',
  getParentRoute: () => rootRouteImport,
} as any)
const EnergyRoute = EnergyRouteImport.update({
  id: '/energy',
  path: '/energy',
  getParentRoute: () => rootRouteImport,
} as any)
const GaitRoute = GaitRouteImport.update({
  id: '/gait',
  path: '/gait',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-summary': typeof AiSummaryRoute
  '/daily': typeof DailyRoute
  '/data-quality': typeof DataQualityRoute
  '/energy': typeof EnergyRoute
  '/gait': typeof GaitRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-summary': typeof AiSummaryRoute
  '/daily': typeof DailyRoute
  '/data-quality': typeof DataQualityRoute
  '/energy': typeof EnergyRoute
  '/gait': typeof GaitRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-summary': typeof AiSummaryRoute
  '/daily': typeof DailyRoute
  '/data-quality': typeof DataQualityRoute
  '/energy': typeof EnergyRoute
  '/gait': typeof GaitRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-summary'
    | '/daily'
    | '/data-quality'
    | '/energy'
    | '/gait'
    | '/reports'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-summary'
    | '/daily'
    | '/data-quality'
    | '/energy'
    | '/gait'
    | '/reports'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/ai-summary'
    | '/daily'
    | '/data-quality'
    | '/energy'
    | '/gait'
    | '/reports'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiSummaryRoute: typeof AiSummaryRoute
  DailyRoute: typeof DailyRoute
  DataQualityRoute: typeof DataQualityRoute
  EnergyRoute: typeof EnergyRoute
  GaitRoute: typeof GaitRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-summary': {
      id: '/ai-summary'
      path: '/ai-summary'
      fullPath: '/ai-summary'
      preLoaderRoute: typeof AiSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-quality': {
      id: '/data-quality'
      path: '/data-quality'
      fullPath: '/data-quality'
      preLoaderRoute: typeof DataQualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energy': {
      id: '/energy'
      path: '/energy'
      fullPath: '/energy'
      preLoaderRoute: typeof EnergyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gait': {
      id: '/gait'
      path: '/gait'
      fullPath: '/gait'
      preLoaderRoute: typeof GaitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiSummaryRoute: AiSummaryRoute,
  DailyRoute: DailyRoute,
  DataQualityRoute: DataQualityRoute,
  EnergyRoute: EnergyRoute,
  GaitRoute: GaitRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
