/**
 * Deterministic demo dataset.
 *
 * IMPORTANT: every patient and every value here is FICTIONAL and generated by a
 * seeded pseudo random generator. It exists so the dashboard is fully usable
 * before the smart-insole hardware is connected. Nothing here is a real
 * measurement of a real person.
 *
 * The same generator produces `public/data/rehabilitation_data.csv`
 * (see `scripts/generate-demo-csv.mjs`), which is the file that would be
 * swapped for a database/API query later.
 */

import type { DailyRecord, Patient } from "./types";

export const DEMO_PATIENTS: Patient[] = [
  {
    patient_id: "P001",
    alias: "Demo Patient A (fictional)",
    age_band: "45-54",
    rehab_program: "Post-ACL reconstruction gait retraining",
    enrolled_on: "2026-06-02",
    focus_limb: "Right",
  },
  {
    patient_id: "P002",
    alias: "Demo Patient B (fictional)",
    age_band: "60-69",
    rehab_program: "Post-stroke ambulation programme",
    enrolled_on: "2026-06-14",
    focus_limb: "Left",
  },
  {
    patient_id: "P003",
    alias: "Demo Patient C (fictional)",
    age_band: "30-39",
    rehab_program: "Ankle fracture recovery",
    enrolled_on: "2026-07-01",
    focus_limb: "Left",
  },
  {
    patient_id: "P004",
    alias: "Demo Patient D (fictional)",
    age_band: "55-64",
    rehab_program: "Total knee replacement rehabilitation",
    enrolled_on: "2026-07-19",
    focus_limb: "Right",
  },
];

export const DEMO_DAYS = 30;

/** Mulberry32 — small deterministic PRNG so SSR and client agree. */
function seeded(seed: number) {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function hash(text: string): number {
  let h = 2166136261;
  for (let i = 0; i < text.length; i += 1) {
    h ^= text.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

const round = (value: number, digits = 2) => {
  const factor = 10 ** digits;
  return Math.round(value * factor) / factor;
};

const clamp = (value: number, min: number, max: number) =>
  Math.min(max, Math.max(min, value));

/**
 * The demo window ends on a fixed reference date so the generated CSV file and
 * the in-app dataset always match, and so screenshots stay reproducible.
 */
export const DEMO_REFERENCE_DATE = "2026-08-26";

export function isoDate(date: Date): string {
  return date.toISOString().slice(0, 10);
}

export function demoDateWindow(days = DEMO_DAYS, endDate = DEMO_REFERENCE_DATE): string[] {
  const end = new Date(`${endDate}T00:00:00Z`);
  const out: string[] = [];
  for (let i = days - 1; i >= 0; i -= 1) {
    const d = new Date(end);
    d.setUTCDate(end.getUTCDate() - i);
    out.push(isoDate(d));
  }
  return out;
}

interface PatientProfile {
  baseSteps: number;
  baseSpeed: number;
  baseStride: number;
  baseAsymmetry: number;
  improvement: number;
  reportBias: number;
}

const PROFILES: Record<string, PatientProfile> = {
  P001: { baseSteps: 6800, baseSpeed: 0.98, baseStride: 98, baseAsymmetry: 7.6, improvement: 1, reportBias: 0 },
  P002: { baseSteps: 4200, baseSpeed: 0.74, baseStride: 82, baseAsymmetry: 12.4, improvement: 0.7, reportBias: 8 },
  P003: { baseSteps: 8600, baseSpeed: 1.16, baseStride: 112, baseAsymmetry: 4.2, improvement: 1.2, reportBias: -6 },
  P004: { baseSteps: 5600, baseSpeed: 0.88, baseStride: 91, baseAsymmetry: 9.1, improvement: 0.9, reportBias: 4 },
};

const DEFAULT_PROFILE: PatientProfile = {
  baseSteps: 6000,
  baseSpeed: 0.95,
  baseStride: 95,
  baseAsymmetry: 8,
  improvement: 1,
  reportBias: 0,
};

function buildRecord(patientId: string, date: string, index: number, total: number): DailyRecord {
  const rnd = seeded(hash(`${patientId}-${date}`));
  const profile = PROFILES[patientId] ?? DEFAULT_PROFILE;
  const progress = total > 1 ? index / (total - 1) : 1;
  const weekday = new Date(`${date}T00:00:00Z`).getUTCDay();
  const weekendFactor = weekday === 0 || weekday === 6 ? 0.86 : 1;

  const steps = Math.round(
    profile.baseSteps *
      (1 + 0.16 * profile.improvement * progress) *
      weekendFactor *
      (0.92 + rnd() * 0.16),
  );
  const strideM = (profile.baseStride * (1 + 0.09 * profile.improvement * progress)) / 100;
  const stride_length_cm = round(strideM * 100 * (0.98 + rnd() * 0.04), 1);
  const gait_speed = round(
    profile.baseSpeed * (1 + 0.11 * profile.improvement * progress) * (0.97 + rnd() * 0.06),
    2,
  );
  const distance_km = round((steps * stride_length_cm) / 100000, 2);
  const gait_asymmetry = round(
    clamp(profile.baseAsymmetry * (1 - 0.22 * profile.improvement * progress) * (0.94 + rnd() * 0.12), 1.2, 22),
    1,
  );
  const activity_minutes = Math.round(clamp(steps / 145 + rnd() * 8, 8, 180));
  const energy_harvested_mj = round(steps * 0.0019 * (0.9 + rnd() * 0.2), 2);
  const energy_consumed_mj = round(energy_harvested_mj * (0.62 + rnd() * 0.22), 2);
  const energy_stored_mj = round(
    clamp(6 + (energy_harvested_mj - energy_consumed_mj) * 2.4 + rnd() * 3, 1, 48),
    2,
  );
  const data_completeness = round(clamp(97.6 - rnd() * 6.5, 82, 99.9), 1);

  const pain_score = Math.round(clamp(48 + profile.reportBias - 18 * progress + rnd() * 9, 4, 96));
  const anxiety_score = Math.round(clamp(50 + profile.reportBias - 13 * progress + rnd() * 10, 4, 96));
  const depression_score = Math.round(clamp(38 + profile.reportBias - 11 * progress + rnd() * 9, 3, 92));
  const appetite_score = Math.round(clamp(64 - profile.reportBias + 12 * progress + rnd() * 8, 10, 99));
  const sleep_score = Math.round(clamp(58 - profile.reportBias + 13 * progress + rnd() * 9, 10, 99));
  const general_condition_score = Math.round(
    clamp(60 - profile.reportBias + 15 * progress + rnd() * 7, 10, 99),
  );

  const hours = 9 + Math.floor(rnd() * 10);
  const minutes = Math.floor(rnd() * 60);
  const seconds = Math.floor(rnd() * 60);
  const pad = (n: number) => String(n).padStart(2, "0");

  return {
    patient_id: patientId,
    date,
    steps,
    distance_km,
    gait_speed,
    stride_length_cm,
    gait_asymmetry,
    activity_minutes,
    energy_harvested_mj,
    energy_stored_mj,
    energy_consumed_mj,
    data_completeness,
    pain_score,
    anxiety_score,
    depression_score,
    appetite_score,
    sleep_score,
    general_condition_score,
    last_sample_at: `${date}T${pad(hours)}:${pad(minutes)}:${pad(seconds)}`,
  };
}

/** Full fictional dataset: every patient × every day in the demo window. */
export function buildDemoDataset(days = DEMO_DAYS): DailyRecord[] {
  const dates = demoDateWindow(days);
  const rows: DailyRecord[] = [];
  for (const patient of DEMO_PATIENTS) {
    dates.forEach((date, index) => {
      rows.push(buildRecord(patient.patient_id, date, index, dates.length));
    });
  }
  return rows;
}

export const DAILY_CSV_COLUMNS: (keyof DailyRecord)[] = [
  "patient_id",
  "date",
  "steps",
  "distance_km",
  "gait_speed",
  "stride_length_cm",
  "gait_asymmetry",
  "activity_minutes",
  "energy_harvested_mj",
  "energy_stored_mj",
  "energy_consumed_mj",
  "data_completeness",
  "pain_score",
  "anxiety_score",
  "depression_score",
  "appetite_score",
  "sleep_score",
  "general_condition_score",
  "last_sample_at",
];

export function datasetToCsv(rows: DailyRecord[]): string {
  const header = DAILY_CSV_COLUMNS.join(",");
  const lines = rows.map((row) => DAILY_CSV_COLUMNS.map((col) => String(row[col])).join(","));
  return [header, ...lines].join("\n");
}

/** Tolerant CSV parser used when the dataset is loaded from a CSV file. */
export function parseDailyCsv(csv: string): DailyRecord[] {
  const lines = csv.trim().split(/\r?\n/);
  if (lines.length < 2) return [];
  const header = lines[0]!.split(",").map((h) => h.trim());
  const numeric = new Set(
    DAILY_CSV_COLUMNS.filter((c) => c !== "patient_id" && c !== "date" && c !== "last_sample_at"),
  );

  return lines.slice(1).flatMap<DailyRecord>((line) => {
    if (!line.trim()) return [];
    const cells = line.split(",");
    const row: Record<string, string | number> = {};
    header.forEach((key, i) => {
      const raw = (cells[i] ?? "").trim();
      if (numeric.has(key as keyof DailyRecord)) {
        const value = Number(raw);
        row[key] = Number.isFinite(value) ? value : 0;
      } else {
        row[key] = raw;
      }
    });
    if (!row["patient_id"] || !row["date"]) return [];
    return [row as unknown as DailyRecord];
  });
}
